# Generated by Django 4.0.3 on 2023-06-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_address_city_address_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addressCoustemId',
            new_name='contacktPersonNumber',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contacktPersonNumer',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contactPersonName',
        ),
    ]
