# Generated by Django 4.2.2 on 2023-06-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoustemSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=50)),
                ('Coustmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namepasnes', models.CharField(help_text='الاسم التجاري', max_length=20, null=True)),
                ('namescient', models.CharField(help_text='الاسم العلمي', max_length=20, null=True)),
                ('manufactureCompany', models.CharField(help_text='الشركة المصنعة', max_length=20, null=True)),
                ('desc', models.CharField(help_text='وصف المنتج', max_length=10)),
                ('quntity', models.CharField(help_text='كمية المنتج', max_length=10)),
                ('Created_at', models.DateField(help_text='تاريخ انشاء المنتج', max_length=20)),
                ('dataFinshProdect', models.DateField(help_text='تارخ انتهاء المنتج', max_length=20)),
                ('photo', models.ImageField(null=True, upload_to='photos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coustemCatogry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodect.coustemsections')),
                ('prodect_CoustmerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='productOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOffers', models.CharField(help_text='اسم العرض', max_length=20)),
                ('quntity_of_start_Offers', models.CharField(help_text='كمية', max_length=10)),
                ('amount_increase', models.CharField(help_text=' كمية الزيادة', max_length=10)),
                ('price_with_increase', models.FloatField(help_text=' سعر البيع مع العرض', max_length=10, null=True)),
                ('offers_prodectIid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodect.products')),
            ],
        ),
    ]
