# Generated by Django 4.0.3 on 2023-06-07 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustemsections',
            name='Coustmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coustmerSections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='coustemCatogry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='prodect.coustemsections'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prodect_CoustmerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
