# Generated by Django 4.0.3 on 2023-06-14 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_coustmerId', models.CharField(blank=True, default='', max_length=10)),
                ('Created_at', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_address', models.CharField(blank=True, default='', max_length=30)),
                ('order_status', models.CharField(blank=True, default='', max_length=20)),
                ('orderType', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=100)),
                ('payment_status', models.CharField(blank=True, default='', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('ordersTotalPrice', models.CharField(blank=True, default='', max_length=10)),
                ('delivery_charge', models.CharField(blank=True, default='', max_length=10)),
                ('order_amount', models.CharField(blank=True, default='', max_length=10)),
                ('delivery_Employe', models.CharField(blank=True, default='', max_length=20)),
                ('commission', models.CharField(blank=True, default='', max_length=10)),
                ('order_number', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
   ]
