# Generated by Django 4.0.3 on 2023-06-14 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prodect_id', models.CharField(max_length=10)),
                ('order_number', models.CharField(blank=True, default='', max_length=10)),
                ('price', models.CharField(blank=True, default='', max_length=10)),
                ('quntity', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.CharField(blank=True, default='', max_length=20)),
                ('update_at', models.CharField(blank=True, default='', max_length=20)),
                ('coustmerid', models.CharField(blank=True, default='', max_length=10)),
                ('vendor', models.CharField(blank=True, max_length=10)),
                ('isExist', models.BooleanField(default=False, max_length=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
